### PR TITLE
feat: poem entity basic function

### PR DESCRIPTION
**Pull request by lee-garden**

### CODE REVIEW

**Comment by YooInKeun** [comment]
@97e57e I confirmed your Pull Request.

[fix] 
- I propose to change data type of spentTime in Poem Class `Integer` to `Float or Double` for flexibility.

[question]
- Why is there `@NoArgsConstructor` annotation in Poem Class? How about deleting `@NoArgsConstructor` and `constructor` of Poem Class and adding `@AllArgsConstructor` annotation?

Thank you for reading my comment.

**Comment by YooInKeun** [comment]
@97e57e  I confirmed your Pull Request.

[fix] 
- I propose to change data type of spentTime in `Poem Class` and `PoemSaveRequestDto Class` `Integer` to `Float or Double` for flexibility.

[question]
- Why are there `@NoArgsConstructor` annotation and `@Column(nullable = false)` together in `Poem Class`? How about deleting `@NoArgsConstructor` and `@Builder` of `Poem Class` and adding `@AllArgsConstructor` annotation to guarantee creating poem object having content and spentTime. This is the same in `PoemSaveRequestsDto Class`. 

Please let me know if there's anything wrong with me. Thank you for reading my comment.

**Comment by lee-garden** [comment]
@YooInKeun 
`@NoArgsConstructor` is required for Hibernate to create proxy object
- what is proxy object
https://stackoverflow.com/questions/25340606/what-does-the-hibernate-proxy-object-contain

`nullable = false` is NOT NULL CONSTRAINT for datbase, not related to Object

`@Builder` is required for creating object
Because we use ORM, we need to deal with Objects

**Comment by YooInKeun** [comment]
@97e57e 

Thank you for your answer.
This has been merged into `develop`.
Let's discuss `spentTime data type` at the next meeting :)

**Pull request merged**
